#define CHECK(n, c) if (!(c)) { return n; }
struct P { int x; int y; };
struct L { int v[3]; struct { int a; } in; };
struct F { int v[3]; int tail; };
static int g = 4; extern int e; int e = 5;
int tentative; int tentative;
typedef int Pair[2];
typedef struct Node { int v; struct Node *next; } Node;
union U { int i; float f; };
enum E { A = 3, B, C = 10, D }; int values[] = { A, B, C, D };
static_assert(sizeof(int) == 4, "int is 32 bits");
enum { K = 6 };
constexpr int KC = 6;
int main(void) {
int a, b = 2, *p = &b;
CHECK(1, b == 2 && *p == 2 && p == &b);
int arr[5] = { 1, 2 };
CHECK(2, arr[1] == 2 && arr[2] == 0 && arr[4] == 0);
int sized[] = { 1, 2, 3 };
CHECK(3, sizeof sized == 12 && sized[2] == 3);
int des[4] = { [2] = 5, [0] = 1 };
CHECK(4, des[0] == 1 && des[1] == 0 && des[2] == 5 && des[3] == 0);
struct P s = { .y = 2, .x = 1 }; struct P z = { 0 };
CHECK(5, s.x == 1 && s.y == 2 && z.x == 0 && z.y == 0);
struct L l = { { 1, 2, 3 }, { 4 } };
CHECK(6, l.v[2] == 3 && l.in.a == 4);
struct F f = { 1, 2, 3, 4 };
CHECK(7, f.v[2] == 3 && f.tail == 4);
int x = 3; int y = x * 2; int w = y + x;
CHECK(8, w == 9);
int k[K];
CHECK(9, sizeof k == 24 && KC == 6);
char str[8] = "hi";
CHECK(10, str[1] == 'i' && str[2] == 0 && str[7] == 0 && sizeof str == 8);
int (*pa)[3] = &sized;
CHECK(11, (*pa)[2] == 3 && sizeof *pa == 12);
CHECK(12, g + e == 9);
tentative = 3;
CHECK(13, tentative == 3);
Pair pr = { 3, 4 };
CHECK(14, pr[0] + pr[1] == 7 && sizeof(Pair) == 8);
Node n2 = { 2, 0 }; Node n1 = { 1, &n2 };
CHECK(15, n1.next->v == 2 && n1.next->next == 0);
union U u = { .f = 1.0f };
CHECK(16, u.i == 0x3f800000 && sizeof u == 4);
CHECK(17, values[1] == 4 && values[3] == 11 && sizeof values == 16);
auto ax = 5; auto ad = 1.5;
CHECK(18, ax == 5 && sizeof ax == 4 && ad == 1.5 && sizeof ad == 8);
typeof(x) tx = 2; typeof(&x) tp = &tx;
CHECK(19, *tp == 2 && sizeof tx == 4);
const int ci = 9; volatile int vi = 1; vi = vi + ci;
CHECK(20, ci == 9 && vi == 10);
    return 0;
}
